I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/lev2_math.rpy", line 9, in script call
    call game2_math pass (complete = 5, toadd =3, err_check = 3, right_check=3)
  File "game/lev2_math.rpy", line 87, in script call
    call game2_math pass (complete = 5, toadd=toadd, err_check = end_check, right_check=right_check)
  File "game/lev2_math.rpy", line 14, in script
    label game2_math(complete = 5, toadd = 3, err_check = 3, right_check=0):
  File "game/lev2_math.rpy", line 87, in <module>
    call game2_math pass (complete = 5, toadd=toadd, err_check = end_check, right_check=right_check)
NameError: name 'end_check' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/lev2_math.rpy", line 9, in script call
    call game2_math pass (complete = 5, toadd =3, err_check = 3, right_check=3)
  File "game/lev2_math.rpy", line 87, in script call
    call game2_math pass (complete = 5, toadd=toadd, err_check = end_check, right_check=right_check)
  File "game/lev2_math.rpy", line 14, in script
    label game2_math(complete = 5, toadd = 3, err_check = 3, right_check=0):
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 1409, in execute
    args, kwargs = self.arguments.evaluate()
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\ast.py", line 184, in evaluate
    kwargs[k] = renpy.python.py_eval(v, locals=scope)
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Aleksandra\Documents\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/lev2_math.rpy", line 87, in <module>
    call game2_math pass (complete = 5, toadd=toadd, err_check = end_check, right_check=right_check)
NameError: name 'end_check' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
KnowledgeIsland 1.0
Tue Dec 11 20:58:47 2018
