I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/lev1_geo.rpy", line 23, in script
    if country in countries_dict[country_new].values():
  File "game/lev1_geo.rpy", line 23, in <module>
    if country in countries_dict[country_new].values():
AttributeError: 'unicode' object has no attribute 'values'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/lev1_geo.rpy", line 23, in script
    if country in countries_dict[country_new].values():
  File "D:\ren'py\renpy-7.1.1-sdk\renpy\ast.py", line 1760, in execute
    if renpy.python.py_eval(condition):
  File "D:\ren'py\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "D:\ren'py\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/lev1_geo.rpy", line 23, in <module>
    if country in countries_dict[country_new].values():
AttributeError: 'unicode' object has no attribute 'values'

Windows-8-6.2.9200
Ren'Py 7.1.1.929
KnowledgeIsland 1.0
Mon Nov 19 17:54:48 2018
