I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/english.rpy", line 60, in script
    return start
  File "game/english.rpy", line 60, in <module>
    return start
NameError: name 'start' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/english.rpy", line 60, in script
    return start
  File "C:\Users\Олеся\Anaconda projects\НИС\renpy-7.1.1-sdk\renpy\ast.py", line 1454, in execute
    renpy.store._return = renpy.python.py_eval(self.expression)
  File "C:\Users\Олеся\Anaconda projects\НИС\renpy-7.1.1-sdk\renpy\python.py", line 1944, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "C:\Users\Олеся\Anaconda projects\НИС\renpy-7.1.1-sdk\renpy\python.py", line 1937, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/english.rpy", line 60, in <module>
    return start
NameError: name 'start' is not defined

Windows-8-6.2.9200
Ren'Py 7.1.1.929
KnowledgeIsland 1.0
Wed Nov 14 13:24:52 2018
